name: NSE Daily Update
on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: '30 13 * * *' # Runs daily at 7:00 PM IST

jobs:
  update_sheet:
    runs-runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Dependencies
        run: pip install pandas selenium webdriver-manager gspread google-auth

      - name: Execute Script
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: python nse.py
